require 'kubernetes_node_inputs'

control 'SV-242402' do
  title 'The Kubernetes API Server must have an audit log path set.'
  desc 'When Kubernetes is started, components and user services are started
for auditing startup events, and events for components and services, it is
important that auditing begin on startup. Within Kubernetes, audit data for all
components is generated by the API server. To enable auditing to begin, an
audit policy must be defined for the events and the information to be stored
with each event. It is also necessary to give a secure location where the audit
logs are to be stored. If an audit log path is not specified, all audit data is
sent to studio.'
  desc 'check', 'Change to the /etc/kubernetes/manifests directory on the Kubernetes Control Plane. Run the command:
grep -i audit-log-path *

If the "--audit-log-path" is not set, this is a finding.'
  desc 'fix', 'Edit the Kubernetes API Server manifest file in the /etc/kubernetes/manifests directory on the Kubernetes Control Plane.

Set the value of "--audit-log-path" to a secure location for the audit logs to be written.

Note: If the API server is running as a Pod, then the manifest will also need to be updated to mount the host system filesystem where the audit log file is to be written.'
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000092-CTR-000165'
  tag gid: 'V-242402'
  tag rid: 'SV-242402r960888_rule'
  tag stig_id: 'CNTR-K8-000610'
  tag fix_id: 'F-45635r927101_fix'
  tag cci: ['CCI-001464']
  tag nist: ['AU-14 (1)']

  only_if("This control applies only to control-plane nodes; input('node_roles') must include 'control-plane'.", impact: 0.0) do
    KubernetesNodeInputs.value('node_roles', input('node_roles')).include?('control-plane')
  end

  kube_apiserver_manifest = kubernetes_manifest(::File.join(KubernetesNodeInputs.value('manifests_path', input('manifests_path')), 'kube-apiserver.yaml'), 'kube-apiserver')
  describe kube_apiserver_manifest do
    its('errors') { should be_empty }
  end

  audit_log_path = Array(kube_apiserver_manifest.params['audit-log-path']).join

  describe 'Kubernetes API Server audit log path' do
    subject { audit_log_path }
    it { should_not be_empty }
  end
end
